from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from pipeline.config import BUG_REPORT_DIR
from pipeline.llm.client import LLMClient


class BugReport(BaseModel):
    """
    Structured bug report generated by AI.
    """

    model_config = ConfigDict(extra="forbid")

    title: str = Field(min_length=1)
    severity: str = Field(min_length=1)
    priority: str = Field(min_length=1)
    description: str = Field(min_length=1)
    steps_to_reproduce: list[str] = Field(min_length=1)
    expected_result: str = Field(min_length=1)
    actual_result: str = Field(min_length=1)


BUG_REPORT_PROMPT = """
Ты — Senior QA Engineer.

На основании анализа выполнения теста
сформируй баг-репорт.

Используй только предоставленную информацию.

Верни только JSON.

Формат:

{{
  "title": "",
  "severity": "",
  "priority": "",
  "description": "",
  "steps_to_reproduce": [],
  "expected_result": "",
  "actual_result": ""
}}

Правила:

1. Не придумывай информацию,
   которой нет в анализе.

2. severity должна быть:
   low
   medium
   high
   critical

3. priority должна быть:
   low
   medium
   high
   critical

4. steps_to_reproduce всегда массив строк.

AI анализ:

{analysis}
""".strip()


def load_prompt() -> str:
    return BUG_REPORT_PROMPT


FIRST_FENCE = "```"


def _strip_fences(text: str) -> str:
    cleaned = text.strip()
    if cleaned.startswith(FIRST_FENCE):
        first_newline = cleaned.find("\n")
        if first_newline != -1:
            cleaned = cleaned[first_newline + 1 :]
    closing = cleaned.rfind(FIRST_FENCE)
    if closing != -1:
        cleaned = cleaned[:closing]
    return cleaned.strip()


class BugReportGenerator:
    """
    Generate structured bug reports using LLM.
    """

    def __init__(self,llm_client: LLMClient) -> None:
        self.llm_client = llm_client

    def generate(self,analysis: dict[str, Any]) -> BugReport:

        prompt = BUG_REPORT_PROMPT.format(analysis=json.dumps(analysis,ensure_ascii=False,indent=2))

        response = self.llm_client.generate(prompt)

        return self._parse_response(response)

    @staticmethod
    def _parse_response(response: str) -> BugReport:

        data = json.loads(_strip_fences(response))

        return BugReport.model_validate(data)

    @staticmethod
    def save(report: BugReport, test_case_id: str) -> Path:
        BUG_REPORT_DIR.mkdir(parents=True, exist_ok=True)
        file_path = BUG_REPORT_DIR / f"{test_case_id}.json"
        file_path.write_text(report.model_dump_json(indent=2), encoding="utf-8")
        return file_path