from __future__ import annotations

import json
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from pipeline.llm.client import LLMClient


class BugReport(BaseModel):
    """
    Structured bug report generated by AI.
    """

    model_config = ConfigDict(extra="forbid")

    title: str = Field(min_length=1)
    severity: str = Field(min_length=1)
    priority: str = Field(min_length=1)
    description: str = Field(min_length=1)
    steps_to_reproduce: list[str] = Field(min_length=1)
    expected_result: str = Field(min_length=1)
    actual_result: str = Field(min_length=1)


BUG_REPORT_PROMPT = """
Ты — Senior QA Engineer.

На основании анализа выполнения теста
сформируй баг-репорт.

Используй только предоставленную информацию.

Верни только JSON.

Формат:

{{
  "title": "",
  "severity": "",
  "priority": "",
  "description": "",
  "steps_to_reproduce": [],
  "expected_result": "",
  "actual_result": ""
}}

Правила:

1. Не придумывай информацию,
   которой нет в анализе.

2. severity должна быть:
   low
   medium
   high
   critical

3. priority должна быть:
   low
   medium
   high
   critical

4. steps_to_reproduce всегда массив строк.

AI анализ:

{analysis}
""".strip()


class BugReportGenerator:
    """
    Generate structured bug reports using LLM.
    """

    def __init__(self,llm_client: LLMClient) -> None:
        self.llm_client = llm_client

    def generate(self,analysis: dict[str, Any]) -> BugReport:

        prompt = BUG_REPORT_PROMPT.format(analysis=json.dumps(analysis,ensure_ascii=False,indent=2))

        response = self.llm_client.generate(prompt)

        return self._parse_response(response)

    @staticmethod
    def _parse_response(response: str) -> BugReport:

        data = json.loads(response)

        return BugReport.model_validate(data)